terminate called after throwing an instance of 'std::out_of_range'
  what():  stoll
make: *** [Makefile:12: run] Aborted (core dumped)
